spring.application.name=spring-activemq-sfdc


spring.activemq.broker-url=ssl://b-36f76383-e4c1-478b-b417-912c3e84e0ae-1.mq.us-east-1.amazonaws.com:61617
spring.activemq.user=sping_test
spring.activemq.password=Integrations_123