server.port=8082


#My SQl Credentials
spring.datasource.url= jdbc:mysql://spring.cpe6cg0mw5d4.us-east-1.rds.amazonaws.com:3306/springtest
spring.datasource.username=root
spring.datasource.password=rA3p9WawNXKO9vNP8kwY

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=none
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect

spring.mvc.pathmatch.matching-strategy=ant-path-matcher