spring.application.name=spring-activemq-sfdc
server.port:8082

#Active MQ Credentials
spring.activemq.broker-url=ssl://test:61617
spring.activemq.user=sping_test
spring.activemq.password=Integrations_123